### ISSUE TITLE
possible feature

### ISSUE THREAD

**Issue by JohnMica** [paulmassen/grav-theme-story#3]
ON the Portfolio items once you click them, nothing really happens (an image is opened in the same page).

What if we could have a modal opening up with the portfolio image on the right/left and the description with link to the actual URL page ?

Let me know what you think of this and I'll get onto it 😄

**Comment by paulmassen** [comment]
Sure, excellent idea!

**Comment by JohnMica** [comment]
I might disable the existing 'lightbox' since it might not be needed.

**Comment by JohnMica** [comment]
PR merged, functionality added
